name: "Simple composite action"
description: "Test basic features"
inputs:
   repo-secret:
     description: "The repo secret to echo"
     required: true
runs:
  using: "composite"
  steps:
    - name: "ls"
      shell: bash
      run: ls
    - name: "Checkout repo"
      uses: actions/checkout@v3
    - name: "ls after checkout"
      shell: bash
      run: ls
    - name: "Get repo secret"
      shell: bash
      run: |
         echo ${{ inputs.repo-secret }}
         echo $INPUT_REPO-SECRET
