name: "Use custom actions"
on: workflow_dispatch
jobs:
  composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run composite action"
        uses: actions/composite-action@v1
