name: "Push handler"
on:
  push:
    branches: [main]
jobs:
  first:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    environment: myenv
    steps:
      - name: "Echo environment variable from environment 'myenv'"
        run: |
          echo "TEST_VAR value with $ notation:"
          echo "'echo \$TEST_VAR' would not work because the environment variable in 'myenv' is accessible only from vars!"
          echo $TEST_VAR
      - name: "Echo the same variable from context from environment 'myenv'"
        env:
          INTERMEDIATOR_TEST_VAR: ${{ vars.TEST_VAR }}
        run: |
          echo "TEST_VAR value with context notation:"
          echo |
            echo ${{ vars.TEST_VAR }}
            echo $INTERMEDIATOR_TEST_VAR
