name: "push + workflow_call handler"
on:
  push:
    branches: [main]
  workflow_call:
    inputs:
      name:
        type: string
jobs:
  push:
    if: inputs.name == ''
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    environment: myenv
    steps:
      - name: "Echo environment variable from repository"
        run: |
          echo "TEST_REPO_VAR value with $ notation:"
          echo "'echo \$TEST_REPO_VAR' doesn't work because the environment variable in the repo is accessible only from vars:"
          echo $TEST_REPO_VAR
      - name: "Echo the same variable from context from repository"
        env:
          INTERMEDIATOR_TEST_ENV_VAR: ${{ vars.TEST_REPO_VAR }}
        run: |
          echo "TEST_REPO_VAR value with context notation:"
          echo |
            echo ${{ vars.TEST_REPO_VAR }}
            echo $INTERMEDIATOR_TEST_ENV_VAR
      - name: "Echo environment variable from environment 'myenv'"
        run: |
          echo "TEST_ENV_VAR value with $ notation:"
          echo "'echo \$TEST_ENV_VAR' doesn't work because the environment variable in 'myenv' is accessible only from vars:"
          echo $TEST_ENV_VAR
      - name: "Echo the same variable from context from environment 'myenv'"
        env:
          INTERMEDIATOR_TEST_ENV_VAR: ${{ vars.TEST_ENV_VAR }}
        run: |
          echo "TEST_ENV_VAR value with context notation:"
          echo |
            echo ${{ vars.TEST_ENV_VAR }}
            echo $INTERMEDIATOR_TEST_ENV_VAR
  workflow_call:
    if: inputs.name != ''
    runs-on: ubuntu-latest
    steps:
      - name: "Say hi!"
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Hi ${{ inputs.name }}!!!"
