name: "Push handler"
on:
  push:
    branches: [main]
jobs:
  first:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    environment: myenv
    steps:
      - name: "Echo environment variable from environment"
        run: |
          echo "TEST_VAR value with $ notation:"
          echo $TEST_VAR
      - name: "Echo the same variable from context from environment"
        run: |
          echo "TEST_VAR value with context notation:"
          echo ${{ vars.TEST_VAR }}
  
